const headers = {
  groups: [
    { label: "Availability", colspan: 3 },
    { label: "Visibility", colspan: 3 },
  ],
  columns: [
    "Sales",
    "Out of Stock",
    "Total Inventory",
    "Average Rank",
    "Est. Traffic",
    "Est. Impressions",
  ],
};

const tableData = [
  {
    name: "Protein Bar 100g",
    checked: true,
    sales: "₹93,132.12",
    "out of stock": "1.68%",
    "total inventory": 931.9,
    "average rank": 3.2,
    "est. traffic": 12303,
    "est. impressions": 25005,
    changes: {
      sales: "+2.4%",
      "out of stock": "+2.4%",
      "average rank": "+2.4%",
      "est. traffic": "+2.4%",
      "est. impressions": "+2.4%",
    },
  },
  {
    name: "Choco Bar 100g",
    checked: true,
    sales: "₹7,012.72",
    "out of stock": "3.28%",
    "total inventory": 328,
    "average rank": 4,
    "est. traffic": 2960,
    "est. impressions": 3657,
    changes: {
      sales: "+2.4%",
      "out of stock": "+2.4%",
      "average rank": "+2.4%",
      "est. traffic": "+2.4%",
      "est. impressions": "+2.4%",
    },
  },
  {
    name: "Energy Drink Can 250ml",
    checked: false,
    sales: "₹18,931.00",
    "out of stock": "5.10%",
    "total inventory": 1500,
    "average rank": 2.5,
    "est. traffic": 8500,
    "est. impressions": 18900,
    changes: {
      sales: "-1.2%",
      "out of stock": "+0.6%",
      "average rank": "-0.5%",
      "est. traffic": "-1.4%",
      "est. impressions": "-2.1%",
    },
  },
  {
    name: "Granola Pack 500g",
    checked: false,
    sales: "₹25,312.45",
    "out of stock": "0.85%",
    "total inventory": 1120,
    "average rank": 1.9,
    "est. traffic": 9500,
    "est. impressions": 21000,
    changes: {
      sales: "+4.5%",
      "out of stock": "-0.8%",
      "average rank": "+0.9%",
      "est. traffic": "+3.1%",
      "est. impressions": "+3.7%",
    },
  },
  {
    name: "Protein Shake 500ml",
    checked: true,
    sales: "₹36,800.50",
    "out of stock": "2.20%",
    "total inventory": 2040,
    "average rank": 3.7,
    "est. traffic": 13900,
    "est. impressions": 32200,
    changes: {
      sales: "+1.1%",
      "out of stock": "+0.3%",
      "average rank": "+1.2%",
      "est. traffic": "+2.2%",
      "est. impressions": "+2.5%",
    },
  },
  {
    name: "Fiber Cookies 200g",
    checked: false,
    sales: "₹12,450.30",
    "out of stock": "1.00%",
    "total inventory": 870,
    "average rank": 5.0,
    "est. traffic": 4000,
    "est. impressions": 9500,
    changes: {
      sales: "-0.8%",
      "out of stock": "+0.2%",
      "average rank": "-0.4%",
      "est. traffic": "-0.9%",
      "est. impressions": "-1.1%",
    },
  },
];

const footerData = {
  sales: "₹2,93,132.12",
  "out of stock": "16%",
  "total inventory": 2931,
  "average rank": "8.3",
  "est. traffic": "61,985",
  "est. impressions": "2,61,768",
};

export { headers, footerData, tableData };
